name: YskLib
version: '${project.version}'
main: org.yusaki.lib.YskLib
api-version: '1.20'
author: Yusaki
description: A library plugin for Yusaki's plugins
folia-supported: true
softdepend:
  - ItemEdit
