name: Release YskLib

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout YskLib
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build YskLib release (no build number)
      run: mvn clean package -DskipTests

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: target/YskLib-*.jar
        generate_release_notes: true
